Locale: en
CompatibilityMode: true
SinkRateTicks: 20
SinkCheckTicks: 100
TracerRateTicks: 5
PilotTool: 280
WorldGuardBlockMoveOnBuildPerm: true
WorldGuardBlockSinkOnPVPPerm: true
ManOverBoardTimeout: 30
FireballLifespan: 6
FireballPenetration: true
DisableSpillProtection: false
RequireCreatePerm: false
TNTContactExplosives: true
DisableCrates: false
FadeWrecksAfter: 0
#Detect Crafts within loaded chunks (and pilot them; making them sinkable
ShipChunkDetection: true
ShipDetectCheckTicks: 10 # number of minutes to wait before running the ShipChunkDetection
#Ships are always piloted once piloted
PersistentPilot: true
LastDamageRequirement: 10 # number minutes to wait before allowing a craft's blocks to be recalculated after damage
#Allow Maintenance Signs  (Takes the craft offline even in a PersistentPilot mode)
AllowMaintenance: false
#Allow Crafts to be repaired without having blocks in chests
FreeRepair: false
RepairTicksPerBlock: 10
RepairMoneyPerBlock: 10
MaintenanceAllow: false
BlockQueueChunkSize: 1000
AllowCrewSigns: true
SetHomeToCrewSign: false
WGCustomFlagsUsePilotFlag: false
WGCustomFlagsUseMoveFlag: false
WGCustomFlagsUseRotateFlag: false
WGCustomFlagsUseSinkFlag: false
TownyBlockMoveOnSwitchPerm: false
TownyBlockSinkOnNoPVP: false
TownyWorldHeightLimits:
  world:
    worldMin: -1
    worldMax: -1
    aboveTownSpawn: 96
    underTownSpawn: 255